---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - "argoproj.io"
  resources:
  - workflowtaskresults
  verbs:
  - create
  - get
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd
