---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: zwave-backup
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 0
  suspend: false
  workflowSpec:
    volumes:
    - name: talos-secrets
      secret:
        secretName: talos-secrets
    entrypoint: main
    templates:
    - name: main
      steps:
        - - name: call-talos-template
            templateRef:
              name: talos-backup-template
              template: main
            arguments:
              parameters:
              - name: slack_message
                value: "zwave-js-ui snapshot complete"
              - name: talos_directory
                value: "/var/mnt/storage/zwave/backups/store"
              - name: minio_path
                value: "zwave-js-ui"
