---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: esphome
spec:
  vaultAuthRef: esphome
  mount: secret/
  type: kv-v2
  path: esphome
  refreshAfter: 60s
  destination:
    create: true
    name: esphome
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: esphome
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: esphome
    serviceAccount: default
