apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: windmill
  namespace: windmill
spec:
  #defaultBackend:
  #  service:
  #    name: windmill-app
  #    port:
  #      number: 8000
  ingressClassName: tailscale
  rules:

  - host: windmill # windmill.king-gila.ts.net
    http:
      paths:
      - backend:
          service:
            name: windmill-lsp
            port:
              number: 3001
        path: /ws/
        pathType: Prefix
  - host: windmill
    http:
      paths:
      - backend:
          service:
            name: windmill-app
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - windmill
