apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-optimizer

resources:
  - namespace.yaml
  - vault.yaml
  - network-optimizer.yaml
  - pv.yaml
  - pvc.yaml
  - tailscale.yaml
