apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-optimizer-data
  namespace: network-optimizer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: network-optimizer-data
