---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt-upstairs-cert
  namespace:  zigbee2mqtt
spec:
  secretName: zigbee2mqtt-upstairs-cert
  commonName: "zig-upstairs.kube.marcyoung.us"
  dnsNames:
  - zig-upstairs.kube.marcyoung.us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
