apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-upstairs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /var/mnt/storage/zigbee2mqtt-upstairs
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/usb-08_0781_5597.present
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
