apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - vault.yaml

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: kube-system
  version: 6.24.3
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    logLevel: debug
    crd:
      create: true
    aws:
      credentials:
        secretName: "external-dns"
