---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: external-dns
spec:
  vaultAuthRef: external-dns
  mount: secret/
  type: kv-v2
  path: external-dns
  refreshAfter: 60s
  destination:
    create: true
    name: external-dns
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: external-dns
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: external-dns
    serviceAccount: external-dns
