---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner
  namespace: actions-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: kubernetes.io/hostname
      #          operator: In
      #          values:
      #          - cluster14
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        resources:
          requests:
            cpu: 30m
            memory: 128M
          limits:
            cpu: 30m
            memory: 128M
        env:
        - name: RUNNER_SCOPE
          value: "repo"
        - name: REPO_URL
          value: "https://github.com/myoung34/homelab"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-runner
              key: ACCESS_TOKEN
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: actions-runner
        securityContext:
          privileged: true
