---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner
  namespace: actions-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cluster14
      volumes:
      - name: containerdsock
        hostPath:
          path: /run/containerd/containerd.sock
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: START_DOCKER_SERVICE
          value: "true"
        - name: RUNNER_SCOPE
          value: "repo"
        - name: REPO_URL
          value: "https://github.com/myoung34/homelab"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-runner
              key: ACCESS_TOKEN
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: actions-runner
        securityContext:
          privileged: true
        volumeMounts:
        - name: containerdsock
          mountPath: /run/containerd/containerd.sock
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 2
            memory: 256Mi
