---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner
  namespace: actions-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: runners
spec:
  replicas: 0
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_SCOPE
          value: "org"
        - name: ORG_NAME
          value: "OctoKode"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-runner
              key: ACCESS_TOKEN
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: actions-runner
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/arch: arm64
