apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hass

resources:
  - namespace.yaml
  - configmap.yaml
  - traefik.yaml
  - le.yaml
  - pv.yaml
  - pvc.yaml
  - vault.yaml
  - hass.yaml
