apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hass

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - vault.yaml
  - hass.yaml
  - tailscale.yaml

configMapGenerator:
- name: hass
  files:
  - files/automations.yaml
  - files/configuration.yaml
  - files/customize.yaml
  - files/groups.yaml
  - files/remove_backup.sh
  - files/scenes.yaml
  - files/scripts.yaml
