---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hass-cert
  namespace:  hass
spec:
  secretName: hass-cert
  commonName: "hass.marcyoung.us"
  dnsNames:
  - hass.marcyoung.us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
