---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hass
spec:
  vaultAuthRef: hass
  mount: secret/
  type: kv-v2
  path: hass
  refreshAfter: 60s
  destination:
    create: true
    name: hass
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: hass
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: hass
    serviceAccount: default
