apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - namespace.yaml
  - vault.yaml
  - le.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  namespace: cert-manager
  version: 0.12.9
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    installCRDs: true
    leaderElection:
      namespace: "cert-manager"
