apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - namespace.yaml
  - vault.yaml
  - le.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  namespace: cert-manager
  version: 1.4.8
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesInline:
    installCRDs: true
    leaderElection:
      namespace: "cert-manager"
