apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    email: myoung34@my.apsu.edu
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: le_cloudflare_api_token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-staging-account-key
    email: myoung34@my.apsu.edu
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: le_cloudflare_api_token
