apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: prowlarr-config
