apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
  - namespace.yaml
  - vault.yaml
  - cr.yaml

helmCharts:
- name: tailscale-operator
  includeCRDs: true
  namespace: tailscale
  releaseName: tailscale
  version: 1.68.1
  repo: https://pkgs.tailscale.com/helmcharts
  valuesInline:
    apiServerProxyConfig:
      mode: "true"
    operatorConfig:
      hostname: "homelab-operator"
