apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
  - namespace.yaml
  - vault.yaml
  - cr.yaml

helmCharts:
- name: tailscale-operator
  includeCRDs: true
  namespace: tailscale
  releaseName: tailscale
  version: 1.61.11
  repo: https://pkgs.tailscale.com/helmcharts
  valuesInline:
    apiServerProxyConfig:
      mode: "true"
    operatorConfig:
      hostname: "homelab-operator"

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: OPERATOR_INITIAL_TAGS
        value: "tag:k8s-operator"
  target:
    kind: Deployment
    namespace: tailscale
    name: operator
