---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale
spec:
  vaultAuthRef: tailscale
  mount: secret/
  type: kv-v2
  path: tailscale
  refreshAfter: 60s
  destination:
    create: true
    name: operator-oauth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: tailscale
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: tailscale
    serviceAccount: operator
