apiVersion: v1
kind: ConfigMap
metadata:
  name: ser2net-zwave
data:
  ser2net.yaml: |
    %YAML 1.1
    ---
    define: &confver 1.0
    define: &banner Connected to port \N(\d)\r\n
    default:
          name: local
          value: true
          class: serialdev
    default:
          name: mdns
          value: false
    default:
          name: mdns-sysattrs
          value: true
    default:
          name: speed
          value: 115200n81
    connection: &con01
      accepter: tcp,3002
      connector: serialdev,/dev/zwave,115200N81
      options:
        kickolduser: true
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ser2net-zwave
  namespace: home-automation
  labels:
    app.kubernetes.io/name: ser2net-zwave
    app.kubernetes.io/instance: rfxcom
  annotations:
    configmap.reloader.stakater.com/reload: "ser2net-zwave"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ser2net-zwave
      app.kubernetes.io/instance: rfxcom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ser2net-zwave
        app.kubernetes.io/instance: rfxcom
    spec:
      containers:
        - name: ser2net-zwave
          image: jippi/ser2net:latest
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          ports:
            - containerPort: 3002
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ser2net
              name: configmap
            - name: usb-zooz
              mountPath: /dev/zwave
      volumes:
        - configMap:
            name: ser2net-zwave
          name: configmap
        - name: usb-zooz
          hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_baf11d5406caec11b51361a341be1031-if00-port0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/usb-ff_10c4_ea60.present #zooz
                operator: Exists
---
kind: Service
apiVersion: v1
metadata:
  name: ser2net-zwave
  namespace: home-automation
  labels:
    app.kubernetes.io/name: ser2net-zwave
    app.kubernetes.io/instance: rfxcom
spec:
  selector:
    app.kubernetes.io/name: ser2net-zwave
    app.kubernetes.io/instance: rfxcom
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
