esphome:
  name: ble-proxy
  friendly_name: ble-proxy

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

logger:

api:
  encryption:
    key: !secret ble_proxy_key

ota:
- platform: esphome
  password: !secret ota_password

bluetooth_proxy:
  active: True

ble_client:
  # use thingsup ble scanner on android
  # use 'meater' app first to cause it to start showing up as a beacon
  - mac_address: 'B8:1F:5E:AB:4B:60'
    id: meater1
  - mac_address: 'B8:1F:5E:54:99:F7'
    id: meater2

sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: meater1
    name: "MEATER 1 tip temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '째F'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip_temp = (x[0] + (x[1] << 8) + 8.0) / 16.0;
      return (float)((tip_temp * 1.8) + 32);
  - platform: ble_client
    type: characteristic
    ble_client_id: meater1
    name: "MEATER 1 ambient temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '째F'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip = x[0] + (x[1] << 8);
      uint16_t ra = x[2] + (x[3] << 8);
      uint16_t oa = x[4] + (x[5] << 8);
      uint16_t min_val = 48;
      uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
      return (float)((ambient * 1.8) + 32);
  - platform: ble_client
    type: characteristic
    ble_client_id: meater1
    name: "MEATER 1 battery level"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '2adb4877-68d8-4884-bd3c-d83853bf27b8'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    notify: true
    lambda: |-
      uint16_t battery = (x[0] + x[1]) * 10;
      return (float)battery;
  - platform: ble_client
    type: characteristic
    ble_client_id: meater2
    name: "MEATER 2 tip temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '째F'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip_temp = (x[0] + (x[1] << 8) + 8.0) / 16.0;
      return (float)((tip_temp * 1.8) + 32);
  - platform: ble_client
    type: characteristic
    ble_client_id: meater2
    name: "MEATER 2 ambient temperature"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '7edda774-045e-4bbf-909b-45d1991a2876'
    icon: 'mdi:thermometer'
    unit_of_measurement: '째F'
    accuracy_decimals: 2
    notify: true
    lambda: |-
      uint16_t tip = x[0] + (x[1] << 8);
      uint16_t ra = x[2] + (x[3] << 8);
      uint16_t oa = x[4] + (x[5] << 8);
      uint16_t min_val = 48;
      uint16_t ambient = (tip + std::max(0, (((ra - std::min(min_val, oa)) * 16 * 589) / 1487)) + 8.0) / 16;
      return (float)((ambient * 1.8) + 32);
  - platform: ble_client
    type: characteristic
    ble_client_id: meater2
    name: "MEATER 2 battery level"
    service_uuid: 'a75cc7fc-c956-488f-ac2a-2dbc08b63a04'
    characteristic_uuid: '2adb4877-68d8-4884-bd3c-d83853bf27b8'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    notify: true
    lambda: |-
      uint16_t battery = (x[0] + x[1]) * 10;
      return (float)battery;
