esphome:
  name: front-porch-switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

logger:
  level: VERBOSE
  baud_rate: 0

api:
  encryption:
    key: !secret front_porch_switch_key

ota:
- platform: esphome
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: front_porch_switch_signal
    update_interval: 15s

switch:
  - platform: gpio
    id: "relay"
    name: "front_porch_relay"
    pin: 12
    on_turn_on:
      then:
        - switch.turn_on: relay
        - output.turn_on: status_led
    on_turn_off:
      then:
        - switch.turn_off: relay
        - output.turn_off: status_led

output:
  - platform: esp8266_pwm
    id: status_led
    pin:
      number: GPIO4
      inverted: True

binary_sensor:
  - platform: gpio
    name: "front_porch_switch"
    pin:
      number: 13
      inverted: True
    on_press:
      - switch.toggle: relay
