esphome:
  name: garage-switch
  platform: ESP8266
  board: esp01_1m

wifi:
 ssid: !secret wifi_ssid
 password: !secret wifi_password
 domain: !secret wifi_domain

# Enable logging
logger:

# Enable Home Assistant API
api:
 encryption:
   key: !secret garage_switch_key

ota:
- platform: esphome
  password: !secret ota_password

switch:
  - platform: gpio
    name: "garage"
    pin: 5
