---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 9Gi
  hostPath:
    path: /var/mnt/storage/kubevirt/scratch
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-scratch
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  volumeName: scratch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 9Gi
  hostPath:
    path: /var/mnt/storage/kubevirt/ubuntu
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "ubuntu"
spec:
  storage:
    accessModes:
      - ReadWriteMany
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: ubuntu
    resources:
      requests:
        storage: 8Gi
  source:
    http:
      url: "https://cloud-images.ubuntu.com/jammy/20240227/jammy-server-cloudimg-amd64.img"
