from __future__ import annotations

from sim import MONO0, T0, fixture, klippy_log, stats_series

from printer_agent import gcode, thermal
from printer_agent import klipper_config as kc
from printer_agent import klippy_log as kl
from printer_agent.taxonomy import load_taxonomy

TAX = load_taxonomy()


# ------------------------------------------------------------------ klippy.log


def test_sessions_anchor_wall_clock_and_classify_shutdown() -> None:
    text = klippy_log(
        fixture("enderbig.cfg"),
        stats=stats_series(20, start=10),
        events=[
            (25.0, "Transition to shutdown state: Lost communication with MCU 'mcu'"),
        ],
    )
    log = kl.parse(text, TAX)
    assert len(log.sessions) == 1
    s = log.sessions[0]
    assert s.version == "v0.12.0-450-gabcdef"
    assert s.start_wall == T0 and s.anchored_by == "start_line"
    assert len(s.stats) == 20
    assert s.stats[0].groups["extruder"]["temp"] == 21.0
    assert s.stats[0].groups["_"]["sysload"] == 0.3  # host-wide keys normalized
    sd = s.shutdown
    assert sd is not None and sd.failure_class == "FIRMWARE.mcu_disconnect"
    # Placed at the last Stats eventtime before it, flagged approximate.
    assert sd.wall is not None and abs(sd.wall - (T0 + 25.0 - 1)) < 1.01 and sd.approximate
    assert kc.parse(s.config_text or "").value("bltouch", "z_offset") == "3.420"


def test_restart_starts_new_session_and_gcode_dump() -> None:
    text = klippy_log(
        fixture("enderbig.cfg"),
        events=[(5, "Heater extruder not heating at expected rate")],
        gcode_dump=["G1 X1 E1", "G1 X2 E1"],
    )
    text += f"Start printer at Thu Oct  1 13:00:00 2026 ({T0 + 4000:.1f} {MONO0 + 4000:.1f})\n"
    log = kl.parse(text, TAX)
    assert len(log.sessions) == 2
    assert [g for _, g in log.sessions[0].gcode_dump] == ["G1 X1 E1", "G1 X2 E1"]
    assert log.sessions[1].start_wall == T0 + 4000


def test_tail_without_start_line_uses_live_offset() -> None:
    text = "Stats 5000.0: gcodein=0  extruder: target=0 temp=21.0 pwm=0.000\nProbe triggered prior to movement\n"
    log = kl.parse(text, TAX, truncated=True, live_offset=T0)
    s = log.sessions[0]
    assert s.anchored_by == "live_offset"
    ev = s.events[0]
    assert ev.failure_class == "PROBE.probe_triggering_too_early"
    assert ev.wall == T0 + 5000.0


def test_link_trend_and_heater_trace() -> None:
    text = klippy_log(
        fixture("enderbig.cfg"), stats=stats_series(60, retransmit_fn=lambda i: i * 10, extruder=(200.0, 200.0, 0.5))
    )
    s = kl.parse(text, TAX).sessions[0]
    trend = kl.link_trend(s)
    assert trend is not None and trend["retransmit_bytes"] == 590
    assert len(kl.heater_trace(s, "extruder")) == 60


def test_tmc_and_config_error_signatures() -> None:
    m = TAX.match("TMC 'extruder' reports error: DRV_STATUS: 00180000 s2vsb=1(ShortToSupply_B!)")
    assert m and m[0].failure_class == "MOTION.driver_fault" and m[1]["stepper"] == "extruder"
    m = TAX.match("Option 'sensor_pin' in section 'bltouch' must be specified")
    assert m and m[0].failure_class == "FIRMWARE.configuration_error"
    assert TAX.domain("PROBE.probe_configuration") == "configuration"
    assert TAX.domain("MOTION.binding") == "mechanical"


# ----------------------------------------------------------------------- G-code

PRUSA_GCODE = """; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-10-01 at 12:00:00 UTC
G90 ; use absolute coordinates
M83 ; extruder relative mode
M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm / sec
M104 S150
M140 S60
M190 S60
G28 ; home all axis
BED_MESH_CALIBRATE LOAD=default ; calculate mesh bed
G1 Z50 F240
M104 S215
M109 S215
G1 Z0.6 F240
G92 E0
G1 X2.0 Y140 E10 F1500 ; prime the nozzle
;LAYER_CHANGE
;Z:0.2
G1 X100 Y100 Z0.2 F3000
G1 X120 Y100 E1.2 F1200
G1 X400 Y100 E5.0 F1200
PRINT_END
; prusaslicer_config = begin
; gcode_flavor = marlin
; first_layer_temperature = 215
; temperature = 210
; bed_temperature = 60
; first_layer_bed_temperature = 60
; z_offset = 0
; default_acceleration = 4000
; prusaslicer_config = end
"""


def test_gcode_findings_against_real_config() -> None:
    cfg = kc.parse(fixture("enderbig.cfg"))
    rep = gcode.inspect(PRUSA_GCODE, cfg)
    codes = {f["code"]: f for f in rep.findings}
    assert "LOAD" in codes["bed_mesh_bad_param"]["message"]
    assert "BED_MESH_PROFILE LOAD=default" in codes["bed_mesh_bad_param"]["message"]
    assert codes["gcode_flavor"]["failure_class"] == "SLICER.incorrect_profile"
    assert rep.marlin_only == {"M201": 1, "M203": 1}
    assert rep.unknown_commands == {"PRINT_END": 1}
    assert codes["out_of_range"]["failure_class"] == "MOTION.out_of_range"  # X400 > 353
    assert "accel_above_limit" in codes
    assert rep.slicer and rep.slicer.startswith("generated by PrusaSlicer")
    assert rep.first_extrusion_line is not None


def test_homing_twice_via_macro_is_explained() -> None:
    cfg = kc.parse(fixture("enderbig.cfg") + "\n[gcode_macro PRINT_START]\ngcode:\n  G28\n  BED_MESH_CALIBRATE\n")
    # place the macro above SAVE_CONFIG so it parses as a user section
    text = fixture("enderbig.cfg").replace(
        "[pause_resume]", "[gcode_macro PRINT_START]\ngcode:\n  G28\n\n[pause_resume]"
    )
    cfg = kc.parse(text)
    rep = gcode.inspect("G28\nPRINT_START\nM109 S200\nG1 X10 Y10 E1\n", cfg)
    msgs = {f["code"]: f["message"] for f in rep.findings}
    assert "multiple_homing" in msgs and "PRINT_START (macro contains G28)" in msgs["multiple_homing"]


def test_extrude_before_wait_and_no_home() -> None:
    rep = gcode.inspect("M104 S200\nG1 X10 Y10 E2\nM109 S200\n")
    codes = {f["code"] for f in rep.findings}
    assert {"extrude_before_wait", "no_homing"} <= codes


# ---------------------------------------------------------------------- thermal


def test_thermal_stable() -> None:
    temps = [20 + i * 2 for i in range(95)] + [210 + (0.3 if i % 2 else -0.3) for i in range(100)]
    a = thermal.analyse("extruder", temps, [210.0] * len(temps), [0.4] * len(temps))
    assert a.verdict == "stable", a.findings


def test_thermal_oscillation_and_jumps() -> None:
    temps = [210 + (4 if (i // 5) % 2 else -4) for i in range(200)]
    a = thermal.analyse("extruder", temps, [210.0] * 200)
    assert a.verdict == "unstable" and any("oscillating" in f for f in a.findings)
    temps = [21.0] * 50 + [45.0] + [21.0] * 50
    a = thermal.analyse("extruder", temps, [0.0] * 101)
    assert a.verdict == "fault_suspected"


def test_thermal_not_heating_at_full_power() -> None:
    temps = [25.0] * 120
    a = thermal.analyse("extruder", temps, [200.0] * 120, [1.0] * 120)
    assert a.verdict == "fault_suspected" and "saturated" in a.findings[0]


def test_runaway_shape() -> None:
    trace = [{"t": i, "temp": 210 - i * 0.5, "target": 210.0, "pwm": 1.0} for i in range(60)]
    assert thermal.runaway_shape(trace)["shape"] == "falling_at_full_power"
    trace = [{"t": i, "temp": 210.0 + (30 if i == 30 else 0), "target": 210.0, "pwm": 0.4} for i in range(60)]
    assert thermal.runaway_shape(trace)["shape"] == "sensor_jumps"
