apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

patches:
  - target:
      kind: Service
      name: kube-dns
    patch: |-
      - op: remove
        path: "/spec/selector/app.kubernetes.io~1instance"
      - op: remove
        path: "/spec/selector/app.kubernetes.io~1name"
  - target:
      kind: Deployment
      name: coredns
    patch: |-
      - op: remove
        path: "/spec/selector/matchLabels/app.kubernetes.io~1instance"
      - op: remove
        path: "/spec/selector/matchLabels/app.kubernetes.io~1name"


helmCharts:
- name: coredns
  releaseName: coredns
  version: 1.44.3
  includeCRDs: true
  repo: https://coredns.github.io/helm
  valuesInline:
    replicaCount: 2
    k8sAppLabelOverride: "kube-dns"
    fullnameOverride: coredns
    service:
      name: "kube-dns"
      clusterIP: "10.96.0.10"
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30

      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 8.8.8.8
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
