apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

patches:
  - target:
      kind: Service
      name: kube-dns
    patch: |-
      - op: remove
        path: "/spec/selector/app.kubernetes.io~1instance"
      - op: remove
        path: "/spec/selector/app.kubernetes.io~1name"
      - op: replace
        path: "/spec/selector/k8s-app"
        value: "coredns"

helmCharts:
- name: coredns
  releaseName: coredns
  version: 1.37.1
  includeCRDs: true
  repo: https://coredns.github.io/helm
  valuesInline:
    k8sAppLabelOverride: "coredns"
    fullnameOverride: coredns
    service:
      name: "kube-dns"
      clusterIP: "10.96.0.10"
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30

      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    zoneFiles:
    - filename: NodeHosts
      domain: NodeHosts
      contents: |
        192.168.1.19 cluster11
        192.168.1.21 cluster12
        192.168.1.22 cluster13
        192.168.1.23 cluster14
        192.168.1.24 cluster21
        192.168.1.25 cluster22
        192.168.1.26 cluster23
        192.168.1.27 cluster24
        192.168.3.2  bignasty
