apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: obsidian
    app.kubernetes.io/name: obsidian
  name: obsidian
  namespace: obsidian
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: obsidian
    app.kubernetes.io/name: obsidian
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: obsidian
    secret.reloader.stakater.com/reload: obsidian
  labels:
    app.kubernetes.io/instance: obsidian
    app.kubernetes.io/name: obsidian
  name: obsidian
  namespace: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: obsidian
      app.kubernetes.io/name: obsidian
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: obsidian
        app.kubernetes.io/name: obsidian
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: AWS_REGION
          value: us-east
        - name: AWS_DEFAULT_REGION
          value: us-east
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: obsidian
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: obsidian
        image: "y4m4/s3www:v1.0.0"
        imagePullPolicy: IfNotPresent
        command:
        - "/s3www"
        - "-endpoint"
        - "http://minio.consul.marcyoung.us:9000"
        - "-bucket"
        - "obsidian-rendered"
        - "-address"
        - "0.0.0.0:8080"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: obsidian
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
      serviceAccountName: default
