apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian
  namespace: obsidian
spec:
  defaultBackend:
    service:
      name: obsidian
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
  - hosts:
    - obsidian
