apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

resources:
  - namespace.yaml

helmCharts:
- name: reloader
  includeCRDs: true
  namespace: reloader
  releaseName: reloader
  version: 1.0.51
  repo: https://stakater.github.io/stakater-charts
  valuesInline:
    reloader:
      reloadOnCreate: true
      ignoreSecrets: false
