apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

resources:
  - namespace.yaml

helmCharts:
- name: reloader
  includeCRDs: true
  namespace: reloader
  releaseName: reloader
  version: 2.2.3
  repo: https://stakater.github.io/stakater-charts
  valuesInline:
    reloader:
      reloadOnCreate: true
      ignoreSecrets: false
      deployment:
        resources:
          cpu: 15m
          memory: 105M

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: reloader-reloader
      namespace: reloader
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
