apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-upstairs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  volumeName: zigbee2mqtt-upstairs
