---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zigbee2mqtt
spec:
  vaultAuthRef: zigbee2mqtt
  mount: secret/
  type: kv-v2
  path: zigbee2mqtt
  refreshAfter: 60s
  destination:
    create: true
    name: zigbee2mqtt
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: zigbee2mqtt
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: zigbee2mqtt
    serviceAccount: default
