apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluidd
  namespace: fluidd
spec:
  defaultBackend:
    service:
      name: fluidd
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - fluidd
