---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/myoung34/homelab'
        revision: HEAD
        directories:
          - path: "k8s/prod/*"
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/myoung34/homelab.git
        targetRevision: HEAD
        path: "k8s/prod/{{ path.basename }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - SkipDryRunOnMissingResource=true
        automated:
          prune: true
          selfHeal: true
        syncTimeout: 1200
        onSyncTimeout: "retry"
      revisionHistoryLimit: 5
