apiVersion: v1
data:
  application.namespaces: ""
  applicationsetcontroller.enable.leader.election: "false"
  applicationsetcontroller.enable.progressive.syncs: "false"
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  applicationsetcontroller.namespaces: ""
  applicationsetcontroller.policy: sync
  controller.ignore.normalizer.jq.timeout: 1s
  controller.log.format: text
  controller.log.level: info
  controller.operation.processors: "10"
  controller.repo.server.timeout.seconds: "60"
  controller.self.heal.timeout.seconds: "5"
  controller.status.processors: "20"
  controller.sync.timeout.seconds: "1200"
  otlp.address: ""
  redis.server: argocd-redis:6379
  repo.server: argocd-repo-server.argocd.svc.cluster.local:8081
  reposerver.log.format: text
  reposerver.log.level: info
  reposerver.parallelism.limit: "0"
  server.basehref: /
  server.disable.auth: "false"
  server.enable.gzip: "true"
  server.enable.proxy.extension: "false"
  server.insecure: "false"
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: "false"
  server.rootpath: ""
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
