---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-wf-cert
  namespace: argocd
spec:
  secretName: argocd-wf-cert
  commonName: "argowf.marcyoung.us"
  dnsNames:
  - argowf.marcyoung.us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
