---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-cert
  commonName: "argocd.marcyoung.us"
  dnsNames:
  - argocd.marcyoung.us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
