---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd
spec:
  vaultAuthRef: argocd
  mount: secret/
  type: kv-v2
  path: argocd
  refreshAfter: 60s
  destination:
    create: true
    name: argocd-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: argocd
    serviceAccount: default
