apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage

# kustomize build "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.23" >chart.yaml
resources:
  - chart.yaml

patches:
  - target:
      kind: ConfigMap
      name: local-path-config
    patch: |-
      - op: replace
        path: /data
        value:
          config.json: |-
            {
                    "nodePathMap":[
                    {
                            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                            "paths":["/var/mnt/storage"]
                    }
                    ]
            }
          helperPod.yaml: |-
            apiVersion: v1
            kind: Pod
            metadata:
              name: helper-pod
            spec:
              containers:
              - name: helper-pod
                image: busybox
                imagePullPolicy: IfNotPresent
          setup: |-
            #!/bin/sh
            set -eu
            mkdir -m 0777 -p "$VOL_DIR"
          teardown: |-
            #!/bin/sh
            set -eu
            rm -rf "$VOL_DIR"
