apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-2.2.2
  name: traefik-forward-auth
  namespace: traefik
spec:
  ports:
  - name: http
    port: 4181
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/name: traefik-forward-auth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-2.2.2
  name: traefik-forward-auth
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-forward-auth
      app.kubernetes.io/name: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-forward-auth
        app.kubernetes.io/name: traefik-forward-auth
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: AUTH_HOST
          value: dex.marcyoung.us
        - name: DEFAULT_PROVIDER
          value: oidc
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              key: domain
              name: traefik-forward-auth
        - name: LOG_LEVEL
          value: info
        - name: PROVIDERS_OIDC_CLIENT_ID
          value: forward-auth
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: traefik-forward-auth
        - name: PROVIDERS_OIDC_ISSUER_URL
          value: https://dex.marcyoung.us
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: traefik-forward-auth
        - name: TZ
          value: UTC
        - name: WHITELIST
          valueFrom:
            secretKeyRef:
              key: allowlist
              name: traefik-forward-auth
        image: thomseddon/traefik-forward-auth:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 4181
          timeoutSeconds: 1
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 4181
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 4181
          timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://traefik-forward-auth.traefik.svc.cluster.local:4181
    authResponseHeaders:
    - X-Forwarded-User
