apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml
  - vault.yaml
  - middleware.yaml

helmCharts:
- name: traefik
  includeCRDs: true
  namespace: traefik
  releaseName: traefik
  version: 34.3.0
  repo: https://helm.traefik.io/traefik
  valuesInline:
    service:
      enabled: false
    deployment:
      enabled: true
      replicas: 1
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
      access:
        enabled: true
    globalArguments: []
    additionalArguments:
      - "--serverstransport.insecureskipverify=true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        allowExternalNameServices: true
        publishedService:
          enabled: true
        ingressEndpoint:
          ip: "209.30.119.60"
    hub:
      enabled: false
