apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml
  - vault.yaml
  - middleware.yaml
  - lb.yaml

helmCharts:
- name: traefik
  includeCRDs: true
  namespace: traefik
  releaseName: traefik
  version: 34.3.0
  repo: https://helm.traefik.io/traefik
  valuesInline:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - cluster12
    service:
      type: ClusterIP
      externalIPs:
        - 192.168.1.19
        - 192.168.1.21
        - 192.168.1.22
        - 192.168.1.23
        - 192.168.1.24
        - 192.168.1.25
        - 192.168.1.26
        - 192.168.1.27
    deployment:
      enabled: true
      replicas: 1
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
      access:
        enabled: true
    globalArguments: []
    additionalArguments:
      - "--serverstransport.insecureskipverify=true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        allowExternalNameServices: true
        publishedService:
          enabled: true
        ingressEndpoint:
          ip: "209.30.119.60"
    hub:
      enabled: false
