apiVersion: v1
kind: Service
metadata:
  name: traefik-bgp
  namespace: traefik
  labels:
    pool: traefik
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: web
  - name: https
    port: 443
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
