---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: httpredirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: blog-redirect
spec:
  redirectRegex:
    regex: ^https://marcyoung.us/(post/.*)
    replacement: https://markyoung.us/${1}
