---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: traefik
spec:
  vaultAuthRef: traefik
  mount: secret/
  type: kv-v2
  path: traefik
  refreshAfter: 60s
  destination:
    create: true
    name: traefik-forward-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: traefik
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: traefik
    serviceAccount: traefik
