---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: datadog
spec:
  vaultAuthRef: datadog
  mount: secret
  type: kv-v2
  path: datadog
  refreshAfter: 60s
  destination:
    create: true
    name: datadog
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: datadog
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: datadog
    serviceAccount: datadog
