apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mailgun-to-paperless-ngx
    app.kubernetes.io/name: mailgun-to-paperless-ngx
  name: mailgun-to-paperless-ngx
  namespace: mailgun-to-paperless-ngx
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: mailgun-to-paperless-ngx
    app.kubernetes.io/name: mailgun-to-paperless-ngx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mailgun-to-paperless-ngx
    app.kubernetes.io/name: mailgun-to-paperless-ngx
  name: mailgun-to-paperless-ngx
  namespace: mailgun-to-paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mailgun-to-paperless-ngx
      app.kubernetes.io/name: mailgun-to-paperless-ngx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mailgun-to-paperless-ngx
        app.kubernetes.io/name: mailgun-to-paperless-ngx
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: BIND_PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: mailgun-to-paperless-ngx
        image: "ghcr.io/myoung34/mailgun-to-paperless-ngx:latest"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256M
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        name: mailgun-to-paperless-ngx
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: true
      serviceAccountName: default
