apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: descheduler

resources:
  - namespace.yaml

helmCharts:
- name: descheduler
  includeCRDs: true
  namespace: descheduler
  releaseName: descheduler
  version: 0.31.0
  repo: https://kubernetes-sigs.github.io/descheduler/
  valuesInline:
    #schedule: "0 4 */3 * *" # every 3 days at 4am
    schedule: "*/30 * * * *"
    deschedulerPolicy:
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                ignorePvcPods: true
                evictLocalStoragePods: true
            - name: RemoveDuplicates
            - name: PodLifeTime
              args:
                maxPodLifeTimeSeconds: 86400
                namespaces:
                  include:
                  - "actions-runner"
                  - "ser2net"
                  - "http-to-mqtt"
          plugins:
            balance:
              enabled:
                - RemoveDuplicates
            deschedule:
              enabled:
                - PodLifeTime
