apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: descheduler

resources:
  - namespace.yaml

helmCharts:
- name: descheduler
  includeCRDs: true
  namespace: descheduler
  releaseName: descheduler
  version: 0.28.0
  repo: https://kubernetes-sigs.github.io/descheduler/
  valuesInline:
    schedule: "*/30 * * * *"
    deschedulerPolicy:
      strategies:
        PodLifeTime:
          enabled: true
          params:
            podLifeTime:
              maxPodLifeTimeSeconds: 86400 #1 day
            namespaces:
              include:
              - "atlantis"
              - "reloader"
