apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

resources:
  - namespace.yaml
  - vault.yaml
  - sa.yaml
  - tailscale.yaml

helmCharts:
- name: atlantis
  includeCRDs: true
  namespace: atlantis
  releaseName: atlantis
  version: 4.21.1
  repo: https://runatlantis.github.io/helm-charts
  valuesInline:
    orgAllowlist: github.com/myoung34/vps
    service:
      type: ClusterIP
    statefulSet:
      annotations:
        secret.reloader.stakater.com/reload: "atlantis"
    volumeClaim:
      enabled: false
    ingress:
      enabled: false
    test:
      enabled: false
    loadEnvFromSecrets:
      - atlantis
    extraArgs:
    - --write-git-creds
    - --automerge
    - --atlantis-url=https://atlantis.king-gila.ts.net/
    - --repo-allowlist=github.com/myoung34/vps,github.com/myoung34/homelab
    - --port=4141
    - --data-dir=/tmp
    environment: {}
    image:
      # run my automated fork that has my addons
      repository: ghcr.io/myoung34/atlantis
      tag: 'v0.27.1'

patches:
  - target:
      kind: StatefulSet
      name: atlantis
    patch: |-
      - op: remove
        path: "/spec/template/spec/containers/0/env"
