apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

resources:
  - namespace.yaml
  - le.yaml
  - traefik.yaml
  - vault.yaml
  - sa.yaml

helmCharts:
- name: atlantis
  includeCRDs: true
  namespace: atlantis
  releaseName: atlantis
  version: 4.15.1
  repo: https://runatlantis.github.io/helm-charts
  valuesInline:
    orgAllowlist: github.com/myoung34/vps
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: atlantis.marcyoung.us
    statefulSet:
      annotations:
        secret.reloader.stakater.com/reload: "atlantis"
    dataStorage: []
    volumeClaim:
      enabled: false
    ingress:
      enabled: false
    test:
      enabled: false
    loadEnvFromSecrets:
      - atlantis
    extraArgs:
    - --write-git-creds
    - --automerge
    - --atlantis-url=https://atlantis.marcyoung.us/
    - --default-tf-version=v1.5.6
    - --repo-allowlist=github.com/myoung34/vps
    - --port=4141
    - --data-dir=/tmp
    environment: []
    image:
      repository: ghcr.io/myoung34/atlantis

patches:
  - target:
      kind: StatefulSet
      name: atlantis
    patch: |-
      - op: remove
        path: "/spec/template/spec/containers/0/env"
