---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argowf-atlantis-ttl
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argowf-atlantis-ttl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argowf-atlantis-ttl
subjects:
- kind: ServiceAccount
  name: argowf-atlantis-ttl
  namespace: argocd
