---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: atlantis
spec:
  vaultAuthRef: atlantis
  mount: secret/
  type: kv-v2
  path: atlantis
  refreshAfter: 60s
  destination:
    create: true
    name: atlantis
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: atlantis
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: atlantis
    serviceAccount: atlantis
