apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
  - namespace.yaml
  - traefik.yaml
  - vault.yaml
  - tailscale.yaml

helmCharts:
- name: pihole
  includeCRDs: true
  namespace: pihole
  releaseName: pihole
  version: 2.19.0
  repo: https://mojo2600.github.io/pihole-kubernetes/
  valuesInline:
    virtualHost: pihole
    serviceDhcp:
      enabled: false
    serviceDns:
      type: "ClusterIP"
    DNS1: 10.96.0.10
    DNS2: 10.96.0.10
    extraEnvVars:
      CONDITIONAL_FORWARDING: false
      DNSMASQ_LISTENING: all
    admin:
      passwordKey: admin-password
      existingSecret: pihole
    nodeSelector:
      kubernetes.io/hostname: cluster12

    blacklist:
      - "*.googleadservices.com"
      - "*.zip"
      - "*.mov"
