---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
spec:
  address: http://192.168.3.2:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pihole
spec:
  vaultAuthRef: pihole
  mount: secret/
  type: kv-v2
  path: pihole
  refreshAfter: 60s
  destination:
    create: true
    name: pihole
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pihole
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pihole
    serviceAccount: default
