apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /var/mnt/storage/paperless-ngx
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/usb-todo.present
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
