---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: paperless
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
