---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
