apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: kube-state-metrics
  releaseName: kube-state-metrics
  namespace: kube-system
  version: 5.33.2
  includeCRDs: true
  repo: https://prometheus-community.github.io/helm-charts
  valuesInline:
    service:
      clusterIP: "10.96.0.255"
