- alias: Basement Deck Motion Light On
  id: basement_deck_person_motion_light_on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected_2
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.g4_instant_is_dark_2
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.wall_2

- alias: Upstairs Deck Motion Light On
  id: upstairs_deck_person_motion_light_on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.g4_instant_is_dark
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.wall_4
# Turn off basement lights after 30 min no person motion
- alias: Basement Deck Motion Light Off
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected_2
      to: "off"
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.wall_2
# Turn off upstairs deck lights after 30 min no person motion
- alias: Upstairs Deck Motion Light Off
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected
      to: "off"
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.wall_4
# Turn off all outside lights at midnight
- alias: Deck Lights Off At Midnight
  id: deck_lights_off_at_midnight
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.wall_2
          - switch.wall_4
# Stupid eco+ ecobee.
- alias: Set Ecobee From Helper At 6:35am
  trigger:
    - platform: time
      at: "06:35:00"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.main_floor
      data:
        temperature: "{{ states('input_number.ecobee_setpoint') | float }}"

- alias: Set Ecobee From Helper At 11:35pm
  trigger:
    - platform: time
      at: "23:35:00"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.main_floor
      data:
        temperature: "{{ states('input_number.ecobee_setpoint') | float }}"

# doorbell person/package notification
- alias: Front Door Person Detected
  id: front_door_person_detected
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_doorbell_pro_person_detected
      to: "on"
      for:
        seconds: 5
  action:
    - service: rest_command.slack_notify
      data:
        message: >
          🚶 Person detected at the front door
          ({{ now().strftime('%Y-%m-%d %I:%M:%S %p') }})

- alias: Front Door Package Detected
  id: front_door_package_detected
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_doorbell_pro_package_detected
      to: "on"
      for:
        seconds: 5
  action:
    - service: rest_command.slack_notify
      data:
        message: >
          📦 Package detected at the front door
          ({{ now().strftime('%Y-%m-%d %I:%M:%S %p') }})
# smoke detectors from cameras
- alias: Smoke Alarm Detected
  id: smoke_alarm_detected
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.g4_doorbell_pro_smoke_alarm_detected
        - binary_sensor.g4_instant_smoke_alarm_detected
        - binary_sensor.g4_instant_smoke_alarm_detected_2
      to: "on"
      for:
        seconds: 5
  action:
    - service: rest_command.slack_notify
      data:
        message: >
          🚨🚨 SMOKE ALARM DETECTED
          Time: {{ now().strftime('%Y-%m-%d %I:%M:%S %p') }}
