- alias: Basement Deck Motion Light On
  id: basement_deck_person_motion_light_on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected_2
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.g4_instant_is_dark_2
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.wall_2

- alias: Upstairs Deck Motion Light On
  id: upstairs_deck_person_motion_light_on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.g4_instant_is_dark
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.wall_4
# Turn off basement lights after 30 min no person motion
- alias: Basement Deck Motion Light Off
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected_2
      to: "off"
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.wall_2
# Turn off upstairs deck lights after 30 min no person motion
- alias: Upstairs Deck Motion Light Off
  trigger:
    - platform: state
      entity_id: binary_sensor.g4_instant_person_detected
      to: "off"
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.wall_4
# Turn off all outside lights at midnight
- alias: Deck Lights Off At Midnight
  id: deck_lights_off_at_midnight
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.wall_2
          - switch.wall_4
# Stupid eco+ ecobee.
- alias: Set Ecobee From Helper At 6:35am
  trigger:
    - platform: time
      at: "06:35:00"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.main_floor
      data:
        temperature: "{{ states('input_number.ecobee_setpoint') | float }}"

- alias: Set Ecobee From Helper At 11:35pm
  trigger:
    - platform: time
      at: "23:35:00"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.main_floor
      data:
        temperature: "{{ states('input_number.ecobee_setpoint') | float }}"
