name: Check User Permission

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          require: 'write'
