name: Check User Permission

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: morfien101/actions-authorized-user@v3
        with:
          username: ${{ github.actor }}
          org: ${{ github.repo_owner }}
          whitelist: "renovate[bot]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
