name: Check User Permission

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - id: auth_check
        uses: morfien101/actions-authorized-user@v3
        with:
          username: ${{ github.actor }}
          team: "admin"
          org: "OctoKode"
          whitelist: "myoung34,renovate[bot]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: can continue
        shell: bash
        run: |
          if [ ${{ steps.auth_check.outputs.authorized }} != "true" ]; then
            echo "::error title=User Unauthorized::User ${{ github.actor }} is not authorized to run this workflow!"
            exit 1
          fi
