apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bifrost

resources:
  - namespace.yaml
  - vault.yaml
  - configmap.yaml
  - bifrost.yaml
  - pv.yaml
  - pvc.yaml
  - tailscale.yaml
