apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost
  namespace: bifrost
spec:
  defaultBackend:
    service:
      name: bifrost
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
  - hosts:
    - bifrost
