---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bifrost
spec:
  vaultAuthRef: bifrost
  mount: secret/
  type: kv-v2
  path: bifrost
  refreshAfter: 60s
  destination:
    create: true
    name: bifrost
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: bifrost
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: bifrost
    serviceAccount: default
